In [2]:
import pandas as pd

# Sample data
final_df = pd.read_csv("tip.csv")

# Compute mean and variance for each sample
mean_values = []
variance_values = []

for index, row in final_df.iterrows():
    sample_data = row.values
    n = len(sample_data)  # Number of elements in the sample
    mean = sum(sample_data) / n
    
    # Sample variance calculation
    squared_diff_sum = sum((x - mean) ** 2 for x in sample_data)
    variance = squared_diff_sum / (n - 1)  # Sample variance formula
    
    mean_values.append(mean)
    variance_values.append(variance)

# Add mean and variance columns to the DataFrame
final_df['mean'] = mean_values
final_df['sample_variance'] = variance_values

final_df

,Unnamed: 0,total_bill,tip,sex,smoker,day,time,size,mean,sample_variance
0,0,16.990000,1.01,0,0,2,0,2,2.750000,33.882886
1,1,21.360195,1.66,1,0,2,0,3,3.752524,51.623146
2,2,21.010000,3.50,1,0,2,0,3,4.063750,48.508227
3,3,23.680000,3.31,1,0,2,0,2,4.373750,62.380141
4,4,24.590000,3.61,0,0,2,0,4,4.775000,67.327886
...,...,...,...,...,...,...,...,...,...,...
239,239,29.030000,5.92,1,0,1,0,3,34.868750,6897.592784
240,240,27.180000,2.00,0,1,1,0,2,34.147500,7002.905479
241,241,22.670000,2.00,1,1,1,0,2,33.833750,7064.021112
242,242,17.820000,1.75,1,0,1,0,2,33.196250,7153.526684
243,243,18.780000,3.00,0,0,3,0,2,33.722500,7189.433193

In [3]:
import pandas as pd

# Sample data
vector1 = final_df['total_bill']
vector2 = final_df['tip']

# Compute mean for each vector
mean_vector1 = vector1.mean()
mean_vector2 = vector2.mean()

# Compute covariance for the sample
covariance = sum((vector1[i] - mean_vector1) * (vector2[i] - mean_vector2) for i in range(len(vector1))) / (len(vector1) - 1)

print("Covariance between the two vectors:", covariance)

Covariance between the two vectors: 6.570598691157279

In [4]:
import pandas as pd
import math

# Compute means for each vector
mean_vector1 = vector1.mean()
mean_vector2 = vector2.mean()

# Compute the sum of the products of the differences
sum_of_products = sum((vector1[i] - mean_vector1) * (vector2[i] - mean_vector2) for i in range(len(vector1)))

# Compute the sum of the squares of the differences for each vector
sum_of_squares_vector1 = sum((x - mean_vector1) ** 2 for x in vector1)
sum_of_squares_vector2 = sum((y - mean_vector2) ** 2 for y in vector2)

# Compute the square root of the sums of squares
sqrt_sum_of_squares_vector1 = math.sqrt(sum_of_squares_vector1)
sqrt_sum_of_squares_vector2 = math.sqrt(sum_of_squares_vector2)

# Compute correlation
correlation = sum_of_products / (sqrt_sum_of_squares_vector1 * sqrt_sum_of_squares_vector2)

print("Correlation between the two vectors:", correlation)

Correlation between the two vectors: 0.5844613454746339

In [6]:
import pandas as pd
import numpy as np

df = final_df.drop(columns=['Unnamed: 0']).values.T

# Compute covariance matrix
covariance_matrix = np.cov(df)

# Compute correlation matrix
correlation_matrix = np.corrcoef(df)

print("Covariance Matrix:")
print(covariance_matrix)
print("\nCorrelation Matrix:")
print(correlation_matrix)

Covariance Matrix:
[[ 6.60166098e+01  6.57059869e+00  3.72440630e-01  4.01501957e-01
  -3.62015056e-01 -5.30535582e-01  4.20976573e+00  1.54435272e+01
   1.39505672e+03]
 [ 6.57059869e+00  1.91445464e+00  5.90133576e-02  3.99210686e-03
  -1.48084059e-02 -7.56088511e-02  6.43906429e-01  8.11649257e-01
  -1.00063585e+02]
 [ 3.72440630e-01  5.90133576e-02  2.30368346e-01  6.57761587e-04
  -3.48276327e-02 -4.42555488e-02  3.93476354e-02 -2.16652816e-01
  -3.92759851e+01]
 [ 4.01501957e-01  3.99210686e-03  6.57761587e-04  2.36844768e-01
  -1.27521419e-01 -1.20083654e-02 -6.16440667e-02  2.14499122e+00
   4.98283820e+02]
 [-3.62015056e-01 -1.48084059e-02 -3.48276327e-02 -1.27521419e-01
   8.58986035e-01  2.65668218e-01  6.12730217e-02  2.95093316e-01
  -1.11430741e+02]
 [-5.30535582e-01 -7.56088511e-02 -4.42555488e-02 -1.20083654e-02
   2.65668218e-01  2.01848479e-01 -4.41880861e-02  8.63633552e-01
   1.31470999e+02]
 [ 4.20976573e+00  6.43906429e-01  3.93476354e-02 -6.16440667e-02
   6.12730217e-02 -4.41880861e-02  9.04590839e-01  7.86775471e-01
   3.50799385e+01]
 [ 1.54435272e+01  8.11649257e-01 -2.16652816e-01  2.14499122e+00
   2.95093316e-01  8.63633552e-01  7.86775471e-01  8.14175896e+01
   1.84848813e+04]
 [ 1.39505672e+03 -1.00063585e+02 -3.92759851e+01  4.98283820e+02
  -1.11430741e+02  1.31470999e+02  3.50799385e+01  1.84848813e+04
   4.59215510e+06]]

Correlation Matrix:
[[ 1.          0.58446135  0.09550345  0.10153813 -0.04807364 -0.14533666
   0.54476002  0.21064966  0.08012296]
 [ 0.58446135  1.          0.08886206  0.00592854 -0.01154763 -0.12162906
   0.48929878  0.06501098 -0.03374778]
 [ 0.09550345  0.08886206  1.          0.00281595 -0.07829238 -0.2052313
   0.08619482 -0.05002577 -0.03818629]
 [ 0.10153813  0.00592854  0.00281595  1.         -0.28272108 -0.0549211
  -0.13317825  0.48846618  0.47778951]
 [-0.04807364 -0.01154763 -0.07829238 -0.28272108  1.          0.63801929
   0.06951046  0.03528639 -0.05610527]
 [-0.14533666 -0.12162906 -0.2052313  -0.0549211   0.63801929  1.
  -0.10341091  0.21303828  0.13655542]
 [ 0.54476002  0.48929878  0.08619482 -0.13317825  0.06951046 -0.10341091
   1.          0.0916781   0.01721173]
 [ 0.21064966  0.06501098 -0.05002577  0.48846618  0.03528639  0.21303828
   0.0916781   1.          0.95598102]
 [ 0.08012296 -0.03374778 -0.03818629  0.47778951 -0.05610527  0.13655542
   0.01721173  0.95598102  1.        ]]